const { Client } = require('pg');
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');
const { prepareClientsSchema, installClientsApiHook } = require('./clients-backend');
const { prepareOperationsSchema, installOperationsApiHook } = require('./operations-backend');
const { prepareEnterpriseSchema, installEnterpriseApiHook } = require('./enterprise-backend');
const { writeEnterprise } = require('./frontend-source-fix');

const blueprintUrl = process.env.DATABASE_URL_BLUEPRINT;
if (blueprintUrl) process.env.DATABASE_URL = blueprintUrl;
if (!process.env.DATABASE_URL) { console.error('CraneGuard: no existe DATABASE_URL.'); process.exit(1); }
function clientConfig(){return{connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:false,connectionTimeoutMillis:10000}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitForPostgres(){const attempts=Number(process.env.DB_STARTUP_ATTEMPTS||36),delayMs=Number(process.env.DB_STARTUP_DELAY_MS||5000);let lastError;for(let i=1;i<=attempts;i++){const c=new Client(clientConfig());try{await c.connect();await c.query('SELECT 1');await c.end();console.log('CraneGuard: PostgreSQL disponible.');return}catch(e){lastError=e;try{await c.end()}catch{}console.warn(`CraneGuard: esperando PostgreSQL (${i}/${attempts}) · ${e.code||e.message}`);if(i<attempts)await sleep(delayMs)}}throw lastError}
async function syncFirstAdminFromEnv(){const email=String(process.env.FIRST_ADMIN_EMAIL||'admin@mkr.com.mx').trim().toLowerCase(),password=String(process.env.FIRST_ADMIN_PASSWORD||''),fullName=String(process.env.FIRST_ADMIN_NAME||'Administrador MKR').trim();if(password.length<10){console.warn('CraneGuard: FIRST_ADMIN_PASSWORD no configurada; no se sincronizó el administrador.');return}const c=new Client(clientConfig());await c.connect();try{const tc=await c.query("SELECT to_regclass('public.app_users') AS table_name");if(!tc.rows[0]?.table_name)return;const hash=await bcrypt.hash(password,12),x=await c.query('SELECT id FROM app_users WHERE LOWER(email)=LOWER($1) LIMIT 1',[email]);if(x.rowCount)await c.query(`UPDATE app_users SET password_hash=$1,full_name=$2,role='admin',active=TRUE,must_change_password=FALSE,password_changed_at=NOW(),updated_at=NOW() WHERE id=$3`,[hash,fullName,x.rows[0].id]);else await c.query(`INSERT INTO app_users(email,full_name,role,password_hash,active,must_change_password) VALUES($1,$2,'admin',$3,TRUE,FALSE)`,[email,fullName,hash])}finally{await c.end()}}
function installFrontendProduction(){const files=['reporting-actions-99.js','clients-production.js','production-scope.js','operations-production.js','offline-production.js','production-branding.js','sw-production.js'];const enterpriseSource=path.join(__dirname,'enterprise-production.js');if(!files.every(f=>fs.existsSync(path.join(__dirname,f)))||!fs.existsSync(enterpriseSource)){console.warn('CraneGuard: faltan archivos del frontend de producción.');return}const publicDir=path.join(__dirname,'public');if(!fs.existsSync(publicDir))fs.mkdirSync(publicDir,{recursive:true});for(const f of files)fs.copyFileSync(path.join(__dirname,f),path.join(publicDir,f));writeEnterprise(path.join(publicDir,'enterprise-production.js'));const targets=[path.join(__dirname,'index.html'),path.join(publicDir,'index.html')],version='11.0.1',names=['reporting-actions-99.js','clients-production.js','production-scope.js','operations-production.js','enterprise-production.js','offline-production.js','production-branding.js'],tags=names.map(n=>`<script src="/${n}?v=${version}"></script>`).join('');for(const file of targets){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');for(const n of [...names,'reporting-publish-fix.js','reporting-actions-98.js','production-clean-100.js']){const escaped=n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');html=html.replace(new RegExp(`<script[^>]+${escaped}[^>]*><\\/script>`,'gi'),'')}html=html.replace(/\/reporting-production\.js\?v=[^"']+/g,`/reporting-production.js?v=${version}`);html=html.includes('</body>')?html.replace('</body>',`${tags}</body>`):html+tags;fs.writeFileSync(file,html,'utf8')}console.log(`CraneGuard: frontend integral ${version} instalado.`)}
(async()=>{try{await waitForPostgres();await syncFirstAdminFromEnv();await prepareClientsSchema();await prepareOperationsSchema();await prepareEnterpriseSchema();installClientsApiHook();installOperationsApiHook();installEnterpriseApiHook();installFrontendProduction();require('./server.js')}catch(e){console.error('CraneGuard: no se pudo iniciar:',e);process.exit(1)}})();
