const express = require('express');
const { Pool } = require('pg');
const multer = require('multer');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL_BLUEPRINT || process.env.DATABASE_URL,
  ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : false,
  max: 8,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 10000
});
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024 } });

const SQL = `
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SEQUENCE IF NOT EXISTS erp_asset_seq START 1;
CREATE SEQUENCE IF NOT EXISTS erp_policy_seq START 1;
CREATE SEQUENCE IF NOT EXISTS erp_opp_seq START 1;
CREATE SEQUENCE IF NOT EXISTS erp_quote_seq START 1;
CREATE SEQUENCE IF NOT EXISTS erp_cpo_seq START 1;
CREATE SEQUENCE IF NOT EXISTS erp_fin_seq START 1;
CREATE SEQUENCE IF NOT EXISTS erp_part_req_seq START 1;

CREATE TABLE IF NOT EXISTS erp_assets(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_code TEXT UNIQUE NOT NULL DEFAULT ('EQ-CG-'||lpad(nextval('erp_asset_seq')::text,5,'0')),
 client_id UUID REFERENCES erp_clients(id) ON DELETE SET NULL, client_name TEXT NOT NULL, plant_name TEXT, area_name TEXT,
 asset_name TEXT NOT NULL, asset_type TEXT NOT NULL DEFAULT 'Grúa', manufacturer TEXT, model TEXT, serial_number TEXT,
 capacity TEXT, year INTEGER, criticality TEXT DEFAULT 'Media', technical_status TEXT DEFAULT 'GRIS', operational_status TEXT DEFAULT 'Activo',
 next_inspection DATE, notes TEXT, created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_assets_client ON erp_assets(client_id,plant_name);
CREATE TABLE IF NOT EXISTS erp_asset_components(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID NOT NULL REFERENCES erp_assets(id) ON DELETE CASCADE,
 component_type TEXT NOT NULL, name TEXT NOT NULL, manufacturer TEXT, model TEXT, serial_number TEXT, part_number TEXT,
 status TEXT DEFAULT 'GRIS', notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS erp_policies(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), policy_code TEXT UNIQUE NOT NULL DEFAULT ('POL-'||to_char(CURRENT_DATE,'YYYY')||'-'||lpad(nextval('erp_policy_seq')::text,4,'0')),
 client_id UUID REFERENCES erp_clients(id) ON DELETE SET NULL, client_name TEXT NOT NULL, name TEXT NOT NULL, contract_number TEXT,
 start_date DATE, end_date DATE, currency TEXT DEFAULT 'MXN', total_value NUMERIC(16,2) DEFAULT 0, status TEXT DEFAULT 'Vigente',
 notes TEXT, created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS erp_policy_items(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), policy_id UUID NOT NULL REFERENCES erp_policies(id) ON DELETE CASCADE,
 item_code TEXT NOT NULL, description TEXT NOT NULL, service_type TEXT, quantity NUMERIC(14,3) DEFAULT 0, unit TEXT DEFAULT 'SERV',
 unit_price NUMERIC(16,2) DEFAULT 0, consumed_qty NUMERIC(14,3) DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(policy_id,item_code)
);
CREATE TABLE IF NOT EXISTS erp_policy_consumptions(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), policy_item_id UUID NOT NULL REFERENCES erp_policy_items(id) ON DELETE CASCADE,
 order_id UUID REFERENCES op_service_orders(id) ON DELETE SET NULL, quantity NUMERIC(14,3) NOT NULL CHECK(quantity>0), notes TEXT,
 created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS erp_part_requests(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), request_code TEXT UNIQUE NOT NULL DEFAULT ('REQ-PART-'||to_char(CURRENT_DATE,'YYYY')||'-'||lpad(nextval('erp_part_req_seq')::text,5,'0')),
 order_id UUID REFERENCES op_service_orders(id) ON DELETE CASCADE, finding_id UUID REFERENCES op_findings(id) ON DELETE SET NULL,
 product_id UUID REFERENCES warehouse_products(id) ON DELETE SET NULL, description TEXT NOT NULL, quantity NUMERIC(14,3) DEFAULT 1,
 status TEXT DEFAULT 'Pendiente de especificación', notes TEXT, created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS erp_installations(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES op_service_orders(id) ON DELETE CASCADE,
 finding_id UUID REFERENCES op_findings(id) ON DELETE SET NULL, product_id UUID REFERENCES warehouse_products(id) ON DELETE SET NULL,
 quantity NUMERIC(14,3) NOT NULL DEFAULT 1, installed_at TIMESTAMPTZ DEFAULT NOW(), installed_by UUID REFERENCES app_users(id) ON DELETE SET NULL,
 test_result TEXT, evidence JSONB DEFAULT '[]'::jsonb, status TEXT DEFAULT 'Instalado · pendiente reinspección', notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS erp_client_assignments(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), client_id UUID NOT NULL REFERENCES erp_clients(id) ON DELETE CASCADE,
 sales_user_id UUID NOT NULL REFERENCES app_users(id) ON DELETE CASCADE, created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(client_id,sales_user_id)
);
CREATE TABLE IF NOT EXISTS erp_opportunities(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), opportunity_code TEXT UNIQUE NOT NULL DEFAULT ('OPP-'||to_char(CURRENT_DATE,'YYYY')||'-'||lpad(nextval('erp_opp_seq')::text,5,'0')),
 client_id UUID REFERENCES erp_clients(id) ON DELETE SET NULL, client_name TEXT NOT NULL, asset_id UUID REFERENCES erp_assets(id) ON DELETE SET NULL,
 finding_id UUID REFERENCES op_findings(id) ON DELETE SET NULL, title TEXT NOT NULL, solution TEXT, stage TEXT DEFAULT 'Solución definida',
 probability INTEGER DEFAULT 20 CHECK(probability BETWEEN 0 AND 100), estimated_value NUMERIC(16,2) DEFAULT 0, currency TEXT DEFAULT 'MXN',
 owner_user_id UUID REFERENCES app_users(id) ON DELETE SET NULL, next_followup DATE, lost_reason TEXT, notes TEXT,
 created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS erp_customer_quotes(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), quote_code TEXT UNIQUE NOT NULL DEFAULT ('COT-'||to_char(CURRENT_DATE,'YYYY')||'-'||lpad(nextval('erp_quote_seq')::text,5,'0')),
 opportunity_id UUID REFERENCES erp_opportunities(id) ON DELETE SET NULL, client_id UUID REFERENCES erp_clients(id) ON DELETE SET NULL, client_name TEXT NOT NULL,
 currency TEXT DEFAULT 'MXN', subtotal NUMERIC(16,2) DEFAULT 0, tax NUMERIC(16,2) DEFAULT 0, total NUMERIC(16,2) DEFAULT 0,
 valid_until DATE, status TEXT DEFAULT 'Borrador', lines JSONB DEFAULT '[]'::jsonb, notes TEXT, created_by UUID REFERENCES app_users(id) ON DELETE SET NULL,
 created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS erp_customer_orders(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_order_code TEXT UNIQUE NOT NULL DEFAULT ('OC-CLI-'||to_char(CURRENT_DATE,'YYYY')||'-'||lpad(nextval('erp_cpo_seq')::text,5,'0')),
 quote_id UUID REFERENCES erp_customer_quotes(id) ON DELETE SET NULL, client_id UUID REFERENCES erp_clients(id) ON DELETE SET NULL, client_name TEXT NOT NULL,
 external_po_number TEXT, amount NUMERIC(16,2) DEFAULT 0, currency TEXT DEFAULT 'MXN', status TEXT DEFAULT 'Recibida', conditions TEXT, notes TEXT,
 created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS erp_client_approvals(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), client_id UUID REFERENCES erp_clients(id) ON DELETE CASCADE, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL,
 subject TEXT NOT NULL, status TEXT DEFAULT 'Pendiente', requested_by UUID REFERENCES app_users(id) ON DELETE SET NULL,
 decided_by UUID REFERENCES app_users(id) ON DELETE SET NULL, decision_notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), decided_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS erp_financial_documents(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), document_code TEXT UNIQUE NOT NULL DEFAULT ('FIN-'||to_char(CURRENT_DATE,'YYYY')||'-'||lpad(nextval('erp_fin_seq')::text,6,'0')),
 client_id UUID REFERENCES erp_clients(id) ON DELETE SET NULL, client_name TEXT NOT NULL, document_type TEXT NOT NULL,
 external_folio TEXT, order_id UUID REFERENCES op_service_orders(id) ON DELETE SET NULL, customer_order_id UUID REFERENCES erp_customer_orders(id) ON DELETE SET NULL,
 issue_date DATE DEFAULT CURRENT_DATE, due_date DATE, currency TEXT DEFAULT 'MXN', subtotal NUMERIC(16,2) DEFAULT 0, tax NUMERIC(16,2) DEFAULT 0,
 total NUMERIC(16,2) DEFAULT 0, status TEXT DEFAULT 'Emitido', notes TEXT, created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS erp_payments(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), document_id UUID NOT NULL REFERENCES erp_financial_documents(id) ON DELETE CASCADE,
 payment_date DATE DEFAULT CURRENT_DATE, amount NUMERIC(16,2) NOT NULL CHECK(amount>0), reference TEXT, method TEXT, notes TEXT,
 created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS erp_technical_documents(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title TEXT NOT NULL, document_type TEXT NOT NULL, manufacturer TEXT, equipment_family TEXT,
 status TEXT DEFAULT 'Vigente', ai_authorized BOOLEAN DEFAULT TRUE, current_version INTEGER DEFAULT 1,
 created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS erp_technical_document_versions(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), document_id UUID NOT NULL REFERENCES erp_technical_documents(id) ON DELETE CASCADE,
 version_no INTEGER NOT NULL, edition TEXT, revision TEXT, effective_date DATE, filename TEXT, mime_type TEXT, file_data BYTEA,
 text_content TEXT, notes TEXT, created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(document_id,version_no)
);
CREATE TABLE IF NOT EXISTS erp_ai_queries(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES app_users(id) ON DELETE SET NULL, query_text TEXT NOT NULL, context_text TEXT,
 result JSONB NOT NULL DEFAULT '{}'::jsonb, mode TEXT DEFAULT 'Retrieval controlado', created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS erp_portal_links(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID UNIQUE NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
 client_id UUID NOT NULL REFERENCES erp_clients(id) ON DELETE CASCADE, allowed_plants JSONB DEFAULT '[]'::jsonb,
 active BOOLEAN DEFAULT TRUE, created_by UUID REFERENCES app_users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS erp_enterprise_audit(
 id BIGSERIAL PRIMARY KEY, actor_user_id UUID REFERENCES app_users(id) ON DELETE SET NULL, entity_type TEXT NOT NULL, entity_id TEXT,
 action TEXT NOT NULL, detail JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW()
);
`;

const T=v=>String(v??'').trim(); const N=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
async function user(req){const id=req.session?.user?.id;if(!id)return null;return (await pool.query('SELECT id,email,full_name,role,active FROM app_users WHERE id=$1',[id])).rows[0]||null}
const deny=(res,msg='No tienes permisos para esta acción.')=>res.status(403).json({error:msg});
async function aud(u,type,id,action,detail={}){await pool.query('INSERT INTO erp_enterprise_audit(actor_user_id,entity_type,entity_id,action,detail) VALUES($1,$2,$3,$4,$5::jsonb)',[u?.id||null,type,id||null,action,JSON.stringify(detail)])}
async function portalScope(u){if(u?.role!=='client')return null;return (await pool.query('SELECT * FROM erp_portal_links WHERE user_id=$1 AND active=TRUE',[u.id])).rows[0]||null}
function salesRoles(r){return ['sales','sales_manager','direction','admin'].includes(r)}
function adminOps(r){return ['admin','coord','direction','sales_manager'].includes(r)}

async function prepareEnterpriseSchema(){await pool.query(SQL);console.log('CraneGuard: capa enterprise PostgreSQL verificada.');}
function installEnterpriseApiHook(){if(express.application.__cgEnterpriseHook)return;express.application.__cgEnterpriseHook=true;const orig=express.application.listen;express.application.listen=function(...args){register(this);return orig.apply(this,args)}}
function register(app){if(app.__cgEnterpriseRoutes)return;app.__cgEnterpriseRoutes=true;

 app.get('/api/enterprise/bootstrap',async(req,res,next)=>{try{const u=await user(req);if(!u||!u.active)return res.status(401).json({error:'Sesión no válida.'});const ps=await portalScope(u);let clientWhere='',vals=[];if(ps){clientWhere='WHERE a.client_id=$1';vals=[ps.client_id]}
  const [assets,policies,opps,quotes,orders,fin,docs,links]=await Promise.all([
   pool.query(`SELECT a.* FROM erp_assets a ${clientWhere} ORDER BY a.created_at DESC LIMIT 500`,vals),
   pool.query(`SELECT p.*,(SELECT COUNT(*) FROM erp_policy_items i WHERE i.policy_id=p.id)::int item_count FROM erp_policies p ${ps?'WHERE p.client_id=$1':''} ORDER BY p.created_at DESC LIMIT 500`,ps?[ps.client_id]:[]),
   ps?Promise.resolve({rows:[]}):pool.query('SELECT o.*,u.full_name owner_name FROM erp_opportunities o LEFT JOIN app_users u ON u.id=o.owner_user_id ORDER BY o.created_at DESC LIMIT 500'),
   pool.query(`SELECT q.* FROM erp_customer_quotes q ${ps?'WHERE q.client_id=$1':''} ORDER BY q.created_at DESC LIMIT 500`,ps?[ps.client_id]:[]),
   pool.query(`SELECT c.* FROM erp_customer_orders c ${ps?'WHERE c.client_id=$1':''} ORDER BY c.created_at DESC LIMIT 500`,ps?[ps.client_id]:[]),
   pool.query(`SELECT f.*,COALESCE((SELECT SUM(p.amount) FROM erp_payments p WHERE p.document_id=f.id),0)::float paid FROM erp_financial_documents f ${ps?'WHERE f.client_id=$1':''} ORDER BY f.issue_date DESC LIMIT 500`,ps?[ps.client_id]:[]),
   pool.query(`SELECT d.*,(SELECT filename FROM erp_technical_document_versions v WHERE v.document_id=d.id ORDER BY version_no DESC LIMIT 1) filename FROM erp_technical_documents d WHERE d.status<>'Obsoleto' ORDER BY d.updated_at DESC LIMIT 500`),
   u.role==='admin'?pool.query('SELECT l.*,u.email,u.full_name,c.name client_name FROM erp_portal_links l JOIN app_users u ON u.id=l.user_id JOIN erp_clients c ON c.id=l.client_id ORDER BY l.created_at DESC'):Promise.resolve({rows:[]})
  ]);res.json({assets:assets.rows,policies:policies.rows,opportunities:opps.rows,quotes:quotes.rows,customerOrders:orders.rows,financial:fin.rows,documents:docs.rows,portalLinks:links.rows,portal:ps,permissions:{sales:salesRoles(u.role),adminOps:adminOps(u.role),engineering:['engineering','admin'].includes(u.role),admin:u.role==='admin'}})}catch(e){next(e)}});

 app.get('/api/enterprise/assets/:id',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});const a=(await pool.query('SELECT * FROM erp_assets WHERE id=$1',[req.params.id])).rows[0];if(!a)return res.status(404).json({error:'Equipo no encontrado.'});const ps=await portalScope(u);if(ps&&String(ps.client_id)!==String(a.client_id))return deny(res);const c=(await pool.query('SELECT * FROM erp_asset_components WHERE asset_id=$1 ORDER BY created_at',[a.id])).rows;const history=(await pool.query('SELECT order_code,status,scheduled_start,service_type FROM op_service_orders WHERE client_id=$1 AND asset_reference=$2 ORDER BY created_at DESC LIMIT 50',[a.client_id,a.asset_name])).rows;res.json({asset:a,components:c,serviceHistory:history})}catch(e){next(e)}});
 app.post('/api/enterprise/assets',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','coord','engineering'].includes(u.role))return deny(res);const b=req.body||{};if(!T(b.client_name)||!T(b.asset_name))return res.status(400).json({error:'Cliente y nombre del equipo son obligatorios.'});const q=await pool.query(`INSERT INTO erp_assets(client_id,client_name,plant_name,area_name,asset_name,asset_type,manufacturer,model,serial_number,capacity,year,criticality,technical_status,operational_status,next_inspection,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[b.client_id||null,T(b.client_name),T(b.plant_name),T(b.area_name),T(b.asset_name),T(b.asset_type)||'Grúa',T(b.manufacturer),T(b.model),T(b.serial_number),T(b.capacity),b.year?N(b.year):null,T(b.criticality)||'Media',T(b.technical_status)||'GRIS',T(b.operational_status)||'Activo',b.next_inspection||null,T(b.notes),u.id]);await aud(u,'asset',q.rows[0].id,'CREATED');res.status(201).json({asset:q.rows[0]})}catch(e){next(e)}});
 app.patch('/api/enterprise/assets/:id',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','coord','engineering'].includes(u.role))return deny(res);const b=req.body||{};const q=await pool.query(`UPDATE erp_assets SET plant_name=COALESCE($1,plant_name),area_name=COALESCE($2,area_name),asset_name=COALESCE($3,asset_name),asset_type=COALESCE($4,asset_type),manufacturer=COALESCE($5,manufacturer),model=COALESCE($6,model),serial_number=COALESCE($7,serial_number),capacity=COALESCE($8,capacity),criticality=COALESCE($9,criticality),technical_status=COALESCE($10,technical_status),operational_status=COALESCE($11,operational_status),next_inspection=COALESCE($12,next_inspection),notes=COALESCE($13,notes),updated_at=NOW() WHERE id=$14 RETURNING *`,[b.plant_name??null,b.area_name??null,b.asset_name??null,b.asset_type??null,b.manufacturer??null,b.model??null,b.serial_number??null,b.capacity??null,b.criticality??null,b.technical_status??null,b.operational_status??null,b.next_inspection??null,b.notes??null,req.params.id]);if(!q.rowCount)return res.status(404).json({error:'Equipo no encontrado.'});await aud(u,'asset',req.params.id,'UPDATED',b);res.json({asset:q.rows[0]})}catch(e){next(e)}});
 app.post('/api/enterprise/assets/:id/components',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','coord','engineering'].includes(u.role))return deny(res);const b=req.body||{};if(!T(b.name)||!T(b.component_type))return res.status(400).json({error:'Tipo y nombre son obligatorios.'});const q=await pool.query('INSERT INTO erp_asset_components(asset_id,component_type,name,manufacturer,model,serial_number,part_number,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.params.id,T(b.component_type),T(b.name),T(b.manufacturer),T(b.model),T(b.serial_number),T(b.part_number),T(b.status)||'GRIS',T(b.notes)]);await aud(u,'asset_component',q.rows[0].id,'CREATED');res.status(201).json({component:q.rows[0]})}catch(e){next(e)}});

 app.get('/api/enterprise/policies/:id',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});const p=(await pool.query('SELECT * FROM erp_policies WHERE id=$1',[req.params.id])).rows[0];if(!p)return res.status(404).json({error:'Póliza no encontrada.'});const ps=await portalScope(u);if(ps&&String(ps.client_id)!==String(p.client_id))return deny(res);const items=(await pool.query(`SELECT i.*,COALESCE((SELECT SUM(c.quantity) FROM erp_policy_consumptions c WHERE c.policy_item_id=i.id),0)::float actual_consumed FROM erp_policy_items i WHERE i.policy_id=$1 ORDER BY item_code`,[p.id])).rows;res.json({policy:p,items})}catch(e){next(e)}});
 app.post('/api/enterprise/policies',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','sales_manager','sales'].includes(u.role))return deny(res);const b=req.body||{};if(!T(b.client_name)||!T(b.name))return res.status(400).json({error:'Cliente y nombre son obligatorios.'});const q=await pool.query(`INSERT INTO erp_policies(client_id,client_name,name,contract_number,start_date,end_date,currency,total_value,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[b.client_id||null,T(b.client_name),T(b.name),T(b.contract_number),b.start_date||null,b.end_date||null,T(b.currency)||'MXN',N(b.total_value),T(b.status)||'Vigente',T(b.notes),u.id]);await aud(u,'policy',q.rows[0].id,'CREATED');res.status(201).json({policy:q.rows[0]})}catch(e){next(e)}});
 app.post('/api/enterprise/policies/:id/items',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','sales_manager','sales','coord'].includes(u.role))return deny(res);const b=req.body||{};if(!T(b.item_code)||!T(b.description))return res.status(400).json({error:'Código y descripción son obligatorios.'});const q=await pool.query('INSERT INTO erp_policy_items(policy_id,item_code,description,service_type,quantity,unit,unit_price) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[req.params.id,T(b.item_code),T(b.description),T(b.service_type),N(b.quantity),T(b.unit)||'SERV',N(b.unit_price)]);await aud(u,'policy_item',q.rows[0].id,'CREATED');res.status(201).json({item:q.rows[0]})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Ya existe esa partida en la póliza.'});next(e)}});
 app.post('/api/enterprise/policy-items/:id/consume',async(req,res,next)=>{const c=await pool.connect();try{const u=await user(req);if(!u){c.release();return res.status(401).json({error:'Sesión no válida.'})}if(!['admin','coord'].includes(u.role)){c.release();return deny(res)};const qty=N(req.body.quantity);if(qty<=0){c.release();return res.status(400).json({error:'Cantidad inválida.'})}await c.query('BEGIN');const item=(await c.query('SELECT * FROM erp_policy_items WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!item)throw Object.assign(new Error('Partida no encontrada.'),{status:404});const used=N((await c.query('SELECT COALESCE(SUM(quantity),0)::float q FROM erp_policy_consumptions WHERE policy_item_id=$1',[item.id])).rows[0].q);if(used+qty>N(item.quantity))throw Object.assign(new Error('El consumo excede la cantidad contratada.'),{status:409});const q=await c.query('INSERT INTO erp_policy_consumptions(policy_item_id,order_id,quantity,notes,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[item.id,req.body.order_id||null,qty,T(req.body.notes),u.id]);await c.query('COMMIT');await aud(u,'policy_item',item.id,'CONSUMED',{quantity:qty,order_id:req.body.order_id});res.status(201).json({consumption:q.rows[0]})}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(e.status||500).json({error:e.message})}finally{c.release()}});

 app.post('/api/enterprise/part-requests',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','coord','engineering','tech_resp'].includes(u.role))return deny(res);const b=req.body||{};if(!T(b.description))return res.status(400).json({error:'Describe la refacción requerida.'});const q=await pool.query('INSERT INTO erp_part_requests(order_id,finding_id,product_id,description,quantity,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[b.order_id||null,b.finding_id||null,b.product_id||null,T(b.description),N(b.quantity,1),T(b.status)||'Pendiente de especificación',T(b.notes),u.id]);await aud(u,'part_request',q.rows[0].id,'CREATED');res.status(201).json({request:q.rows[0]})}catch(e){next(e)}});
 app.get('/api/enterprise/part-requests',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});const rows=(await pool.query(`SELECT r.*,o.order_code,f.finding_code,p.cg_code,p.name product_name FROM erp_part_requests r LEFT JOIN op_service_orders o ON o.id=r.order_id LEFT JOIN op_findings f ON f.id=r.finding_id LEFT JOIN warehouse_products p ON p.id=r.product_id ORDER BY r.created_at DESC LIMIT 500`)).rows;res.json({requests:rows})}catch(e){next(e)}});
 app.post('/api/enterprise/installations',async(req,res,next)=>{const c=await pool.connect();try{const u=await user(req);if(!u){c.release();return res.status(401).json({error:'Sesión no válida.'})}if(!['admin','coord','tech_resp','engineering','warehouse'].includes(u.role)){c.release();return deny(res)};const b=req.body||{};if(!b.order_id)return res.status(400).json({error:'La OS es obligatoria.'});await c.query('BEGIN');const q=await c.query('INSERT INTO erp_installations(order_id,finding_id,product_id,quantity,installed_by,test_result,evidence,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9) RETURNING *',[b.order_id,b.finding_id||null,b.product_id||null,N(b.quantity,1),u.id,T(b.test_result),JSON.stringify(Array.isArray(b.evidence)?b.evidence:[]),T(b.status)||'Instalado · pendiente reinspección',T(b.notes)]);if(b.finding_id)await c.query("UPDATE op_findings SET status='Pendiente de reinspección',updated_at=NOW() WHERE id=$1",[b.finding_id]);await c.query('COMMIT');await aud(u,'installation',q.rows[0].id,'CREATED');res.status(201).json({installation:q.rows[0]})}catch(e){await c.query('ROLLBACK').catch(()=>{});next(e)}finally{c.release()}});
 app.post('/api/enterprise/findings/:id/close',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','engineering'].includes(u.role))return deny(res);const q=await pool.query("UPDATE op_findings SET status='Cerrado',engineering_validated_by=$1,engineering_validated_at=NOW(),validation_notes=$2,updated_at=NOW() WHERE id=$3 RETURNING *",[u.id,T(req.body.notes),req.params.id]);if(!q.rowCount)return res.status(404).json({error:'Hallazgo no encontrado.'});await aud(u,'finding',req.params.id,'CLOSED_AFTER_REINSPECTION');res.json({finding:q.rows[0]})}catch(e){next(e)}});

 app.post('/api/enterprise/assignments',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','sales_manager'].includes(u.role))return deny(res);const q=await pool.query('INSERT INTO erp_client_assignments(client_id,sales_user_id,created_by) VALUES($1,$2,$3) ON CONFLICT(client_id,sales_user_id) DO NOTHING RETURNING *',[req.body.client_id,req.body.sales_user_id,u.id]);res.status(201).json({assignment:q.rows[0]||null})}catch(e){next(e)}});
 app.post('/api/enterprise/opportunities',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!salesRoles(u.role)&&u.role!=='engineering')return deny(res);const b=req.body||{};if(!T(b.client_name)||!T(b.title))return res.status(400).json({error:'Cliente y oportunidad son obligatorios.'});const q=await pool.query(`INSERT INTO erp_opportunities(client_id,client_name,asset_id,finding_id,title,solution,stage,probability,estimated_value,currency,owner_user_id,next_followup,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[b.client_id||null,T(b.client_name),b.asset_id||null,b.finding_id||null,T(b.title),T(b.solution),T(b.stage)||'Solución definida',N(b.probability,20),N(b.estimated_value),T(b.currency)||'MXN',b.owner_user_id||u.id,b.next_followup||null,T(b.notes),u.id]);await aud(u,'opportunity',q.rows[0].id,'CREATED');res.status(201).json({opportunity:q.rows[0]})}catch(e){next(e)}});
 app.patch('/api/enterprise/opportunities/:id',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!salesRoles(u.role))return deny(res);const b=req.body||{};const q=await pool.query(`UPDATE erp_opportunities SET solution=COALESCE($1,solution),stage=COALESCE($2,stage),probability=COALESCE($3,probability),estimated_value=COALESCE($4,estimated_value),next_followup=COALESCE($5,next_followup),lost_reason=COALESCE($6,lost_reason),notes=COALESCE($7,notes),updated_at=NOW() WHERE id=$8 RETURNING *`,[b.solution??null,b.stage??null,b.probability!==undefined?N(b.probability):null,b.estimated_value!==undefined?N(b.estimated_value):null,b.next_followup??null,b.lost_reason??null,b.notes??null,req.params.id]);if(!q.rowCount)return res.status(404).json({error:'Oportunidad no encontrada.'});res.json({opportunity:q.rows[0]})}catch(e){next(e)}});
 app.post('/api/enterprise/quotes',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!salesRoles(u.role))return deny(res);const b=req.body||{},lines=Array.isArray(b.lines)?b.lines:[];const subtotal=lines.reduce((s,x)=>s+N(x.quantity,1)*N(x.unit_price),0),tax=N(b.tax,subtotal*.16),total=subtotal+tax;const q=await pool.query('INSERT INTO erp_customer_quotes(opportunity_id,client_id,client_name,currency,subtotal,tax,total,valid_until,status,lines,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12) RETURNING *',[b.opportunity_id||null,b.client_id||null,T(b.client_name),T(b.currency)||'MXN',subtotal,tax,total,b.valid_until||null,T(b.status)||'Borrador',JSON.stringify(lines),T(b.notes),u.id]);await aud(u,'quote',q.rows[0].id,'CREATED');res.status(201).json({quote:q.rows[0]})}catch(e){next(e)}});
 app.patch('/api/enterprise/quotes/:id',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!salesRoles(u.role))return deny(res);const b=req.body||{},lines=Array.isArray(b.lines)?b.lines:null;let subtotal=null,tax=null,total=null;if(lines){subtotal=lines.reduce((s,x)=>s+N(x.quantity,1)*N(x.unit_price),0);tax=b.tax!==undefined?N(b.tax):subtotal*.16;total=subtotal+tax}const q=await pool.query(`UPDATE erp_customer_quotes SET status=COALESCE($1,status),valid_until=COALESCE($2,valid_until),lines=COALESCE($3::jsonb,lines),subtotal=COALESCE($4,subtotal),tax=COALESCE($5,tax),total=COALESCE($6,total),notes=COALESCE($7,notes),updated_at=NOW() WHERE id=$8 RETURNING *`,[b.status??null,b.valid_until??null,lines?JSON.stringify(lines):null,subtotal,tax,total,b.notes??null,req.params.id]);res.json({quote:q.rows[0]})}catch(e){next(e)}});
 app.post('/api/enterprise/customer-orders',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!salesRoles(u.role))return deny(res);const b=req.body||{};const q=await pool.query('INSERT INTO erp_customer_orders(quote_id,client_id,client_name,external_po_number,amount,currency,status,conditions,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[b.quote_id||null,b.client_id||null,T(b.client_name),T(b.external_po_number),N(b.amount),T(b.currency)||'MXN',T(b.status)||'Recibida',T(b.conditions),T(b.notes),u.id]);if(b.quote_id)await pool.query("UPDATE erp_customer_quotes SET status='Autorizada',updated_at=NOW() WHERE id=$1",[b.quote_id]);await aud(u,'customer_order',q.rows[0].id,'CREATED');res.status(201).json({customerOrder:q.rows[0]})}catch(e){next(e)}});
 app.post('/api/enterprise/approvals',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});const b=req.body||{};if(!b.client_id||!T(b.entity_type)||!T(b.entity_id)||!T(b.subject))return res.status(400).json({error:'Datos incompletos.'});if(!['admin','sales','sales_manager','coord','engineering'].includes(u.role))return deny(res);const q=await pool.query('INSERT INTO erp_client_approvals(client_id,entity_type,entity_id,subject,requested_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[b.client_id,T(b.entity_type),T(b.entity_id),T(b.subject),u.id]);res.status(201).json({approval:q.rows[0]})}catch(e){next(e)}});
 app.post('/api/enterprise/approvals/:id/decision',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});const ps=await portalScope(u);if(u.role!=='client'&&!['admin','sales_manager'].includes(u.role))return deny(res);const a=(await pool.query('SELECT * FROM erp_client_approvals WHERE id=$1',[req.params.id])).rows[0];if(!a)return res.status(404).json({error:'Autorización no encontrada.'});if(ps&&String(ps.client_id)!==String(a.client_id))return deny(res);const status=['Autorizado','Rechazado'].includes(req.body.status)?req.body.status:null;if(!status)return res.status(400).json({error:'Decisión inválida.'});const q=await pool.query('UPDATE erp_client_approvals SET status=$1,decided_by=$2,decision_notes=$3,decided_at=NOW() WHERE id=$4 RETURNING *',[status,u.id,T(req.body.notes),a.id]);res.json({approval:q.rows[0]})}catch(e){next(e)}});

 app.post('/api/enterprise/financial',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','sales_manager','direction'].includes(u.role))return deny(res);const b=req.body||{};if(!T(b.client_name)||!T(b.document_type))return res.status(400).json({error:'Cliente y tipo son obligatorios.'});const subtotal=N(b.subtotal),tax=b.tax!==undefined?N(b.tax):subtotal*.16,total=b.total!==undefined?N(b.total):subtotal+tax;const q=await pool.query('INSERT INTO erp_financial_documents(client_id,client_name,document_type,external_folio,order_id,customer_order_id,issue_date,due_date,currency,subtotal,tax,total,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *',[b.client_id||null,T(b.client_name),T(b.document_type),T(b.external_folio),b.order_id||null,b.customer_order_id||null,b.issue_date||new Date().toISOString().slice(0,10),b.due_date||null,T(b.currency)||'MXN',subtotal,tax,total,T(b.status)||'Emitido',T(b.notes),u.id]);await aud(u,'financial_document',q.rows[0].id,'CREATED');res.status(201).json({document:q.rows[0]})}catch(e){next(e)}});
 app.post('/api/enterprise/financial/:id/payments',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','sales_manager','direction'].includes(u.role))return deny(res);const amount=N(req.body.amount);if(amount<=0)return res.status(400).json({error:'Monto inválido.'});const q=await pool.query('INSERT INTO erp_payments(document_id,payment_date,amount,reference,method,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[req.params.id,req.body.payment_date||new Date().toISOString().slice(0,10),amount,T(req.body.reference),T(req.body.method),T(req.body.notes),u.id]);const f=(await pool.query('SELECT total,COALESCE((SELECT SUM(amount) FROM erp_payments WHERE document_id=$1),0)::float paid FROM erp_financial_documents WHERE id=$1',[req.params.id])).rows[0];if(f&&N(f.paid)>=N(f.total))await pool.query("UPDATE erp_financial_documents SET status='Pagado',updated_at=NOW() WHERE id=$1",[req.params.id]);res.status(201).json({payment:q.rows[0]})}catch(e){next(e)}});

 app.get('/api/enterprise/documents/:id/download',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).end();const v=(await pool.query('SELECT * FROM erp_technical_document_versions WHERE id=$1',[req.params.id])).rows[0];if(!v||!v.file_data)return res.status(404).json({error:'Archivo no disponible.'});res.setHeader('Content-Type',v.mime_type||'application/octet-stream');res.setHeader('Content-Disposition',`attachment; filename="${String(v.filename||'documento').replace(/"/g,'')}"`);res.send(v.file_data)}catch(e){next(e)}});
 app.post('/api/enterprise/documents',upload.single('file'),async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','engineering'].includes(u.role))return deny(res);const b=req.body||{};if(!T(b.title)||!T(b.document_type))return res.status(400).json({error:'Título y tipo son obligatorios.'});const c=await pool.connect();try{await c.query('BEGIN');const d=(await c.query('INSERT INTO erp_technical_documents(title,document_type,manufacturer,equipment_family,status,ai_authorized,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[T(b.title),T(b.document_type),T(b.manufacturer),T(b.equipment_family),T(b.status)||'Vigente',String(b.ai_authorized)!=='false',u.id])).rows[0];const v=(await c.query('INSERT INTO erp_technical_document_versions(document_id,version_no,edition,revision,effective_date,filename,mime_type,file_data,text_content,notes,created_by) VALUES($1,1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,document_id,version_no,edition,revision,effective_date,filename,mime_type,text_content,notes,created_at',[d.id,T(b.edition),T(b.revision),b.effective_date||null,req.file?.originalname||null,req.file?.mimetype||null,req.file?.buffer||null,T(b.text_content),T(b.notes),u.id])).rows[0];await c.query('COMMIT');await aud(u,'technical_document',d.id,'CREATED');res.status(201).json({document:d,version:v})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch(e){next(e)}});
 app.post('/api/enterprise/documents/:id/versions',upload.single('file'),async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(!['admin','engineering'].includes(u.role))return deny(res);const n=N((await pool.query('SELECT current_version FROM erp_technical_documents WHERE id=$1',[req.params.id])).rows[0]?.current_version,0)+1;const b=req.body||{};const q=await pool.query('INSERT INTO erp_technical_document_versions(document_id,version_no,edition,revision,effective_date,filename,mime_type,file_data,text_content,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,document_id,version_no,edition,revision,effective_date,filename,mime_type,text_content,notes,created_at',[req.params.id,n,T(b.edition),T(b.revision),b.effective_date||null,req.file?.originalname||null,req.file?.mimetype||null,req.file?.buffer||null,T(b.text_content),T(b.notes),u.id]);await pool.query('UPDATE erp_technical_documents SET current_version=$1,updated_at=NOW() WHERE id=$2',[n,req.params.id]);res.status(201).json({version:q.rows[0]})}catch(e){next(e)}});
 app.post('/api/enterprise/ai/search',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});const q=T(req.body.query),ctx=T(req.body.context);if(!q)return res.status(400).json({error:'Escribe una consulta.'});const terms=(q+' '+ctx).toLowerCase().split(/\s+/).filter(x=>x.length>3).slice(0,20);const docs=(await pool.query(`SELECT d.id,d.title,d.document_type,d.manufacturer,d.equipment_family,d.current_version,v.edition,v.revision,v.filename,v.text_content FROM erp_technical_documents d JOIN LATERAL(SELECT * FROM erp_technical_document_versions v WHERE v.document_id=d.id ORDER BY version_no DESC LIMIT 1)v ON TRUE WHERE d.status='Vigente' AND d.ai_authorized=TRUE ORDER BY d.updated_at DESC LIMIT 300`)).rows;const ranked=docs.map(d=>{const txt=(d.title+' '+d.document_type+' '+(d.manufacturer||'')+' '+(d.equipment_family||'')+' '+(d.text_content||'')).toLowerCase();const score=terms.reduce((s,t)=>s+(txt.includes(t)?1:0),0);return {...d,score,snippet:(d.text_content||'').slice(0,700)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,8);const result={mode:'Retrieval controlado',query:q,context:ctx,sources:ranked.map(x=>({document_id:x.id,title:x.title,type:x.document_type,edition:x.edition,revision:x.revision,filename:x.filename,score:x.score,snippet:x.snippet})),message:ranked.length?'Se encontraron fuentes autorizadas relacionadas. La interpretación y decisión técnica requieren validación humana.':'No se encontraron fuentes autorizadas suficientes. Completa la biblioteca o amplía la consulta.'};await pool.query('INSERT INTO erp_ai_queries(user_id,query_text,context_text,result,mode) VALUES($1,$2,$3,$4::jsonb,$5)',[u.id,q,ctx,JSON.stringify(result),result.mode]);res.json(result)}catch(e){next(e)}});

 app.post('/api/enterprise/portal-links',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(u.role!=='admin')return deny(res);const q=await pool.query(`INSERT INTO erp_portal_links(user_id,client_id,allowed_plants,active,created_by) VALUES($1,$2,$3::jsonb,TRUE,$4) ON CONFLICT(user_id) DO UPDATE SET client_id=EXCLUDED.client_id,allowed_plants=EXCLUDED.allowed_plants,active=TRUE,updated_at=NOW() RETURNING *`,[req.body.user_id,req.body.client_id,JSON.stringify(Array.isArray(req.body.allowed_plants)?req.body.allowed_plants:[]),u.id]);res.json({link:q.rows[0]})}catch(e){next(e)}});
 app.get('/api/enterprise/portal',async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:'Sesión no válida.'});if(u.role!=='client')return deny(res);const ps=await portalScope(u);if(!ps)return res.status(403).json({error:'Tu usuario todavía no está vinculado a una cuenta cliente.'});const [client,assets,orders,quotes,fin,approvals]=await Promise.all([pool.query('SELECT * FROM erp_clients WHERE id=$1',[ps.client_id]),pool.query('SELECT * FROM erp_assets WHERE client_id=$1 ORDER BY created_at DESC',[ps.client_id]),pool.query('SELECT order_code,asset_reference,service_type,status,scheduled_start,progress FROM op_service_orders WHERE client_id=$1 ORDER BY created_at DESC LIMIT 100',[ps.client_id]),pool.query("SELECT id,quote_code,total,currency,status,valid_until FROM erp_customer_quotes WHERE client_id=$1 AND status<>'Borrador' ORDER BY created_at DESC",[ps.client_id]),pool.query('SELECT id,document_code,document_type,external_folio,issue_date,due_date,total,currency,status,COALESCE((SELECT SUM(p.amount) FROM erp_payments p WHERE p.document_id=f.id),0)::float paid FROM erp_financial_documents f WHERE client_id=$1 ORDER BY issue_date DESC',[ps.client_id]),pool.query('SELECT * FROM erp_client_approvals WHERE client_id=$1 ORDER BY created_at DESC',[ps.client_id])]);res.json({client:client.rows[0],assets:assets.rows,orders:orders.rows,quotes:quotes.rows,financial:fin.rows,approvals:approvals.rows})}catch(e){next(e)}});
}
module.exports={prepareEnterpriseSchema,installEnterpriseApiHook};
